<script>
var BASE_URL = '<?= base_url(); ?>';
</script>

<!-- plugins | jQuery/Materialize -->
<script src="<?= base_path(); ?>plugins/pace/pace.min.js"></script>
<script src="<?= base_path(); ?>plugins/jquery/jquery.min.js"></script>
<script src="<?= base_path(); ?>plugins/materializecss/materialize.min.js"></script>
<script src="<?= base_path(); ?>plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="<?= base_path(); ?>plugins/jquery/form.js"></script>
<script src="<?= base_path(); ?>plugins/datatable/jquery.dataTables.min.js"></script>

<script src="<?= base_path(); ?>plugins/quill/js/katex.min.js"></script>
<script src="<?= base_path(); ?>plugins/quill/js/highlight.min.js"></script>
<script src="<?= base_path(); ?>plugins/quill/js/quill.min.js"></script>

<!-- scripts | Padrão -->
<script src="<?= base_path(); ?>scripts/materializecss.js"></script>
<script src="<?= base_path(); ?>scripts/storage.js"></script>

<script src="<?= base_path(); ?>scripts/functions.js"></script>
<script src="<?= base_path(); ?>scripts/http/http.js"></script>
<script src="<?= base_path(); ?>scripts/http/request.js"></script>
<script src="<?= base_path(); ?>scripts/form.js"></script>
<script src="<?= base_path(); ?>scripts/datatables.js"></script>

<script src="<?= base_path(); ?>scripts/core.js"></script>
