<!-- fonts -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/material-icons/material-icons.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/muli/muli.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/roboto/roboto.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/icons/icons.css">

<!-- styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/animate.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/materializecss/materialize.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/jquery.dataTables.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/responsive.dataTables.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/datatables.min.css">

<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/katex.min.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/monokai-sublime.min.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/quill.snow.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/quill.bubble.css" />

<!-- others styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/colors.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/style.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/app-sidebar.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/admin/themes/default.css">
