<head>

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

	<meta name="generator" content="<= configuracoes('developer_website'); ?>">
	<meta name="author" content="<= configuracoes('author'); ?>">
	<meta name="DC.publisher" content="<= configuracoes('publisher'); ?>">

	<meta name="description" content="<?= configuracoes('description'); ?>">

	<meta name="keywords" content="<?= configuracoes('keywords'); ?>">
	<meta name="DC.creator.address" content="<= configuracoes('creator_address'); ?>">
	<meta name="custodian" content="<?= configuracoes('custodian'); ?>">
	<meta name="revisit-after" content="<?= configuracoes('revisit_after'); ?>">
	<meta name="rating" content="<?= configuracoes('rating'); ?>">
	<meta name="robots" content="<?= configuracoes('robots'); ?>">

	<meta name="theme-color" content="<?= configuracoes('theme_color'); ?>">
	<meta name="apple-mobile-web-app-status-bar-style" content="<?= configuracoes('theme_color'); ?>">
	<meta name="msapplication-navbutton-color" content="<?= configuracoes('theme_color'); ?>">

	<meta property="og:url" content="<?= configuracoes('url'); ?>" />
	<meta property="og:description" content="<?= configuracoes('description'); ?>">
	<meta property="og:image" content="<?= base_path(); ?>images/perfil/foto.jpg">
	<meta property="og:type" content="curriculo" />
	<meta property="og:locale" content="br" />

	<meta name="DC.title" content="<?= configuracoes('title'); ?>">
	<meta property="og:title" content="<?= configuracoes('title'); ?>" />

	<title> <?= configuracoes('title'); ?> </title>

	<noscript>
		<meta http-equiv="Refresh" content="0; url=<?= base_url(); ?>nojs">
	</noscript>

	<?php require('includes/styles.phtml'); ?>

</head>
